---
# tasks file for image_builder
- name: Setup osbuild server
  ansible.builtin.import_role:
    name: infra.osbuild.setup_server

- name: Conditionally set Osbuild vars
  when: item.value is defined
  ansible.builtin.set_fact: "{{ item.name }}: {{ item.value }}"
  loop:
    - { name: microshift_image_ovn_options_template, value: "{{ lookup('ansible.builtin.template', '../templates/ovn_options.j2') if microshift_image_gateway_interface is defined or microshift_image_external_gateway_interface is defined or microshift_image_mtu is defined | default(None) }}" } # noqa yaml[line-length]
    - { name: microshift_image_crio_proxy_template, value: "{{ lookup('ansible.builtin.template', '../templates/crio_proxy.j2') if microshift_image_crio_proxy is defined | default(None) }}" } # noqa yaml[line-length]
    - { name: microshift_image_pull_secret_template, value: "{{ lookup('ansible.builtin.template', '../templates/pull_secret.j2') if microshift_image_pull_secret is defined | default(None) }}" } # noqa yaml[line-length]

- name: Running osbuild image builder
  ansible.builtin.import_role:
    name: infra.osbuild.builder
  vars:
    builder_custom_repos: "{{ microshift_image_custom_repos | default([]) }}" # noqa var-naming[no-role-prefix]
    builder_blueprint_name: "{{ microshift_image_blueprint_name }}"
    builder_blueprint_src_path: "{{ microshift_image_blueprint_src_path }}"
    builder_compose_type: "{{ microshift_image_compose_type }}"
    pubkey_file: "{{ microshift_image_pubkey }}"
    builder_compose_customizations: "{{ microshift_image_compose_customizations }}"
    additional_kickstart_post: "{{ microshift_kickstart_post }}"
    builder_kickstart_options: "{{ microshift_kickstart_options }}"
    builder_rhsm_repos: "{{ microshift_rhsm_repos }}"
    builder_compose_pkgs: "{{ microshift_image_compose_pkgs }}" # noqa var-naming[no-role-prefix]
